#!/bin/bash

# Script to import recipes into Prismic using the Migration API

# Set your API key and authorization token
API_KEY=""
AUTH_TOKEN=""

# Function to send a recipe to the Prismic API
send_recipe() {
  local recipe_json=$1
  curl -X POST https://migration.prismic.io/documents \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -H "repository: recipestore-com" \
    -H "x-api-key: $API_KEY" \
    -H "Content-Type: application/json" \
    -d "$recipe_json"
}

# Recipe 1: Chocolate Fudge Brownies
recipe1='{"uid":"chocolate-fudge-brownies","title":"Chocolate Fudge Brownies","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Chocolate Fudge Brownies","ingridients":[{"type":"o-list-item","text":"1/2 cup unsalted butter","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup granulated sugar","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 large eggs","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp vanilla extract","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/3 cup unsweetened cocoa powder","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 cup all-purpose flour","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/4 tsp salt","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/4 tsp baking powder","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Preheat oven to 350\u00b0F (175\u00b0C). Grease a 9x9 inch baking pan.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Melt the butter and stir in sugar, eggs, and vanilla.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Beat in cocoa, flour, salt, and baking powder.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Spread batter into prepared pan.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Bake for 20-25 minutes or until a toothpick comes out clean.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eDREAACMABPj4","type":"category","link_type":"Document"},"cook_time":"30 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe1"


# Recipe 2: Lemon Panna Cotta
recipe2='{"uid":"lemon-panna-cotta","title":"Lemon Panna Cotta","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Lemon Panna Cotta","ingridients":[{"type":"o-list-item","text":"2 cups heavy cream","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 cup sugar","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Zest of 1 lemon","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp vanilla extract","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tsp gelatin powder","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"3 tbsp cold water","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"In a saucepan, heat cream, sugar, lemon zest, and vanilla until warm.","spans":[],"direction":"ltr"},{"type":"list-item","text":"In a small bowl, soften gelatin in cold water.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add gelatin to warm cream and stir until dissolved.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Pour mixture into ramekins and chill for 4 hours.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Serve with fresh berries or lemon zest.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eDREAACMABPj4","type":"category","link_type":"Document"},"cook_time":"4 hours","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe2"


# Recipe 3: Coconut Rice Pudding
recipe3='{"uid":"coconut-rice-pudding","title":"Coconut Rice Pudding","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Coconut Rice Pudding","ingridients":[{"type":"o-list-item","text":"1 cup jasmine rice","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cups coconut milk","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup water","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 cup sugar","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp vanilla extract","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/4 tsp salt","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Ground cinnamon for topping","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Combine rice, coconut milk, water, sugar, salt in a saucepan.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Bring to a boil, then reduce heat and simmer until rice is tender.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Stir in vanilla and cook for 5 more minutes.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Serve warm or chilled, topped with cinnamon.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eDREAACMABPj4","type":"category","link_type":"Document"},"cook_time":"40 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe3"


# Recipe 4: Beef Stroganoff
recipe4='{"uid":"beef-stroganoff","title":"Beef Stroganoff","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Beef Stroganoff","ingridients":[{"type":"o-list-item","text":"1 lb beef sirloin, sliced thin","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp olive oil","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 onion, chopped","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cloves garlic, minced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup mushrooms, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup sour cream","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup beef broth","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tbsp flour","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salt and pepper to taste","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Egg noodles","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Cook onions and garlic in olive oil until soft.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add beef and cook until browned.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Stir in mushrooms, cook 5 minutes.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Sprinkle flour, add broth, and bring to a simmer.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Stir in sour cream and simmer 10 minutes.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Serve over cooked egg noodles.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7fqBEAACEABPtx","type":"category","link_type":"Document"},"cook_time":"45 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe4"


# Recipe 5: Creamy Chicken Alfredo
recipe5='{"uid":"creamy-chicken-alfredo","title":"Creamy Chicken Alfredo","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Creamy Chicken Alfredo","ingridients":[{"type":"o-list-item","text":"2 chicken breasts, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tbsp butter","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"3 cloves garlic, minced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup heavy cream","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 cup grated Parmesan cheese","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salt and pepper to taste","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Fettuccine pasta","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Cook fettuccine as per package.","spans":[],"direction":"ltr"},{"type":"list-item","text":"In a pan, cook chicken in butter until golden.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add garlic and saut\u00e9 briefly.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Pour in cream and bring to simmer.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Stir in Parmesan and season.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Combine with pasta and serve hot.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7fqBEAACEABPtx","type":"category","link_type":"Document"},"cook_time":"30 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe5"


# Recipe 6: Stuffed Bell Peppers
recipe6='{"uid":"stuffed-bell-peppers","title":"Stuffed Bell Peppers","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Stuffed Bell Peppers","ingridients":[{"type":"o-list-item","text":"4 bell peppers, tops removed","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 lb ground beef","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup cooked rice","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 onion, chopped","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cups tomato sauce","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp Italian seasoning","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salt and pepper to taste","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 cup shredded cheese","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Preheat oven to 375\u00b0F (190\u00b0C).","spans":[],"direction":"ltr"},{"type":"list-item","text":"Saut\u00e9 onion and beef until browned.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Mix in rice, seasoning, half the sauce.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Fill peppers with mixture and place in baking dish.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Top with remaining sauce and cheese.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Bake for 25-30 minutes until peppers are tender.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7fqBEAACEABPtx","type":"category","link_type":"Document"},"cook_time":"40 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe6"


# Recipe 7: Chickpea Stir Fry
recipe7='{"uid":"chickpea-stir-fry","title":"Chickpea Stir Fry","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Chickpea Stir Fry","ingridients":[{"type":"o-list-item","text":"1 can chickpeas, drained","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 bell pepper, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 zucchini, chopped","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 onion, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tbsp soy sauce","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp olive oil","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp garlic powder","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Cooked rice for serving","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Heat oil in pan and saut\u00e9 onion and bell pepper.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add zucchini and cook until tender.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add chickpeas and soy sauce, stir well.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Season with garlic powder.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Serve over rice.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7ddxEAACEABPgL","type":"category","link_type":"Document"},"cook_time":"20 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe7"


# Recipe 8: Mushroom Spinach Lasagna
recipe8='{"uid":"mushroom-spinach-lasagna","title":"Mushroom Spinach Lasagna","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Mushroom Spinach Lasagna","ingridients":[{"type":"o-list-item","text":"9 lasagna noodles","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cups mushrooms, chopped","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cups spinach","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup ricotta cheese","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 cups marinara sauce","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 cup shredded mozzarella","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp olive oil","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salt and pepper","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Cook lasagna noodles per package.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Saut\u00e9 mushrooms and spinach in olive oil.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Layer noodles, veggies, ricotta, and sauce in baking dish.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Repeat layers and top with mozzarella.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Bake at 375\u00b0F (190\u00b0C) for 30 minutes.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7ddxEAACEABPgL","type":"category","link_type":"Document"},"cook_time":"50 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe8"


# Recipe 9: Grilled Veggie Wrap
recipe9='{"uid":"grilled-veggie-wrap","title":"Grilled Veggie Wrap","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Grilled Veggie Wrap","ingridients":[{"type":"o-list-item","text":"1 zucchini, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 red bell pepper, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 eggplant, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tbsp hummus","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tortilla wrap","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp olive oil","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salt and pepper","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Brush veggies with olive oil, season and grill until tender.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Spread hummus on wrap.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Add grilled veggies and roll tightly.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Cut and serve warm or cold.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7ddxEAACEABPgL","type":"category","link_type":"Document"},"cook_time":"25 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe9"


# Recipe 10: Spicy Chicken Tacos
recipe10='{"uid":"spicy-chicken-tacos","title":"Spicy Chicken Tacos","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Spicy Chicken Tacos","ingridients":[{"type":"o-list-item","text":"2 chicken breasts, shredded","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp chili powder","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp cumin","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 tsp garlic powder","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Corn tortillas","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Salsa and toppings","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp olive oil","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Season chicken with spices.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Cook in olive oil until done.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Warm tortillas, fill with chicken and toppings.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Serve hot.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eWxEAACAABPl7","type":"category","link_type":"Document"},"cook_time":"20 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe10"


# Recipe 11: Paneer Kathi Rolls
recipe11='{"uid":"paneer-kathi-rolls","title":"Paneer Kathi Rolls","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Paneer Kathi Rolls","ingridients":[{"type":"o-list-item","text":"200g paneer, cubed","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 onion, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 bell pepper, sliced","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 tbsp yogurt","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp garam masala","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 tsp turmeric","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Paratha or wrap","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Mint chutney","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Marinate paneer in yogurt and spices.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Saut\u00e9 onion, pepper, and paneer.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Layer onto paratha with chutney.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Roll and serve.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eWxEAACAABPl7","type":"category","link_type":"Document"},"cook_time":"25 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe11"


# Recipe 12: Falafel Pita Pockets
recipe12='{"uid":"falafel-pita-pockets","title":"Falafel Pita Pockets","type":"recipe","tags":[],"lang":"en-us","data":{"title":"Falafel Pita Pockets","ingridients":[{"type":"o-list-item","text":"1 can chickpeas","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1/2 onion, chopped","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"2 garlic cloves","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tsp cumin","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Fresh parsley","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"1 tbsp flour","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Pita bread","spans":[],"direction":"ltr"},{"type":"o-list-item","text":"Tahini sauce","spans":[],"direction":"ltr"}],"steps":[{"type":"list-item","text":"Blend chickpeas, onion, garlic, and herbs.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Form into balls, fry until golden.","spans":[],"direction":"ltr"},{"type":"list-item","text":"Stuff into pita with veggies and tahini.","spans":[],"direction":"ltr"}],"category":{"id":"Z_7eWxEAACAABPl7","type":"category","link_type":"Document"},"cook_time":"30 minutes","image":{"id":"Z_9V2-vxEdbNPG0j"},"author":{"id":"Z_7dGxEAACAABPd9","type":"author","link_type":"Document"}}}'

send_recipe "$recipe12"