// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  recipe_tile: dynamic(() => import("./RecipeList")),
  recipe_view: dynamic(() => import("./RecipeView")),
  rich_text: dynamic(() => import("./RichText")),
};
